
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter_frontend'
    static_configs:
      - targets: ['frontend-ip:9100']

  - job_name: 'node_exporter_backend'
    static_configs:
      - targets: ['backend-ip:9100']
